### GENERAL SETTINGS ###

# Site settings
title: Steffan T. Padel
description: "A skilled programmer."
baseurl: "" #important: start with /
url: "https://sthomasp.github.io"

# Build settings
markdown: kramdown
permalink: /blog/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

fonts:
  headings: Roboto
  body: Karla

colors:  #in hex code if not noted else
  primary: "#800000" #"#F70031"
  primary_rgb: "128,0,0" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#000000" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
